Minor recipe fixes
conda-forge/zappend-feedstock pull request #2
Opened 2024-01-30 10:34 UTC by pont-us

- Use {{ name }} substitution for package name in PyPI source URL.

- Fix typo in about.summary field.

- Bump build number from 0 to 1.

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2024-01-30 10:44 UTC, thomasstorm approved these changes

2024-01-30 10:47 UTC, forman requested changes

2024-01-30 10:47 UTC, forman commented on recipe/meta.yaml
> +  summary: Tool for creating and updating a Zarr datacube from smaller slices
```suggestion
  summary: Tool for creating and updating Zarr datacubes from smaller slices
```

2024-01-30 10:47 UTC, forman commented on recipe/meta.yaml
> +  summary: Tool for creating and updating a Zarr datacube from smaller slices
Because it can also create a second cube.

2024-01-30 11:10 UTC, forman approved these changes

2024-01-30 11:12 UTC, TejasMorbagal approved these changes

2024-02-01 10:56 UTC, TonioF approved these changes

2024-02-01 10:56 UTC, merged